<a href="https://colab.research.google.com/github/lollolzz/Colab/blob/main/Ch1%20%ED%8C%8C%EC%9D%B4%EC%8D%AC%20%EB%8D%B0%EC%9D%B4%ED%84%B0%20%EB%B6%84%EC%84%9D%20%EA%B8%B0%EC%B4%88/2_Numpy_%EC%8B%A4%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
"""
날짜 : 2021/10/18
이름 : 권능한
내용 : 파이썬 Numpy 패키지 실습하기

Numpy 라이브러리
- 고성능의 수치계산을 위한 파이썬 라이브러리
- 파이썬의 기본 리스트보다 월등한 연산 성능
- 행렬이나 대규모 다차원 배열 처리를 지원
"""

import numpy as np


In [ ]:
# numpy 벡터
v1 = np.array([1,2,3,4,5,])
print('v1 :',v1)

v2 = np.arange(5)
print('v2 :', v2)

v3 = np.arange(10)
print('v3 :',v3)

v1 : [1 2 3 4 5]
v2 : [0 1 2 3 4]
v3 : [0 1 2 3 4 5 6 7 8 9]


In [ ]:
# 0 ~ 1 사이의 임의의 실수 100개
import numpy as np

result1 = np.random.rand(100)

# 표준정규분포를 따르는 실수 100개
result2 = np.random.randn(100)

# 0 -9 사이의 임의의 정수
result3 = np.random.randint(10)
result1, result2, result3

(array([0.01206346, 0.83286159, 0.95992599, 0.86563349, 0.95680725,
        0.81098596, 0.97049374, 0.99851143, 0.60819963, 0.56543406,
        0.97822418, 0.90223975, 0.49169284, 0.77128234, 0.55742364,
        0.91867634, 0.07907474, 0.37600166, 0.3962582 , 0.75556825,
        0.60504962, 0.42900895, 0.52508739, 0.11257421, 0.83742216,
        0.04166445, 0.3725626 , 0.66423209, 0.63195707, 0.18021371,
        0.64155268, 0.79276794, 0.15532876, 0.47626126, 0.51566649,
        0.56361447, 0.06858701, 0.55037995, 0.45004832, 0.81428225,
        0.25612121, 0.41782767, 0.55328215, 0.82686102, 0.53921361,
        0.17929175, 0.19350721, 0.3948181 , 0.48533345, 0.08437429,
        0.56469998, 0.85877477, 0.02047496, 0.58416928, 0.01152797,
        0.08605626, 0.69463028, 0.89069252, 0.78440141, 0.89682727,
        0.55239329, 0.31916574, 0.31979043, 0.83472204, 0.88260928,
        0.82074479, 0.72886662, 0.98599423, 0.62567314, 0.57896263,
        0.68306263, 0.17460067, 0.18963993, 0.69

In [ ]:
# numpy 행렬
m1 = np.array([[1,2],[3,4,]])
print(m1)

m2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(m2)

m3 = np.array([2, 4])

m4 = np.zeros([3, 4])
print(m4)

[[1 2]
 [3 4]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
# 행렬 인덱싱
mat = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(mat)

print(mat[0, 0])
print(mat[0, :])
print(mat[:, 0])

print(mat[0:2, 0:2])
print(mat[:, 0:2])
print(mat[:, 2:4])
print(mat[1:3, 1:3])



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1
[1 2 3 4]
[1 5 9]
[[1 2]
 [5 6]]
[[ 1  2]
 [ 5  6]
 [ 9 10]]
[[ 3  4]
 [ 7  8]
 [11 12]]
[[ 6  7]
 [10 11]]
